version: '3.8'

services:
  delivery-front:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: delivery-front
    ports:
      - "9526:9526"

    environment:
      - PORT=9526
    restart: always
