version: '3.8'

services:
  biblioteca-front:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: delivery-front
    ports:
      - "9536:9536"
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - PORT=9536
    restart: always
